/**
 * Mock data — active while VITE_MOCK_MODE=true
 * Replace with Supabase queries when credentials are available
 */

export const CATEGORY_GROUPS = [
  {
    id: 'creativos',
    label: 'Creativos',
    subcategories: ['Marketing', 'UX/UI', 'Audiovisual', 'Servicios Digitales'],
  },
  {
    id: 'educacion',
    label: 'Educación',
    subcategories: ['Cursos', 'Talleres', 'Mentorías'],
  },
  {
    id: 'tecnologia',
    label: 'Tecnología',
    subcategories: ['Móviles', 'Tablets', 'Laptops', 'Gadgets', 'Gaming', 'Electrónicos'],
  },
  {
    id: 'moda',
    label: 'Moda & Lifestyle',
    subcategories: ['Moda', 'Accesorios', 'Estilo de Vida', 'Belleza', 'Bienestar'],
  },
  {
    id: 'productos-cr',
    label: 'Productos CR',
    subcategories: ['Alimentos', 'Artesanía', 'Hecho a mano'],
  },
  {
    id: 'local',
    label: 'Local → Online',
    subcategories: ['Local → Online'],
  },
]

export const ACCENT_COLORS = {
  black:  { bg: '#000000', text: '#ffffff' },
  red:    { bg: '#ef4444', text: '#ffffff' },
  yellow: { bg: '#f59e0b', text: '#000000' },
  blue:   { bg: '#3b82f6', text: '#ffffff' },
  green:  { bg: '#10b981', text: '#ffffff' },
  white:  { bg: '#ffffff', text: '#000000' },
  purple: { bg: '#8b5cf6', text: '#ffffff' },
  orange: { bg: '#f97316', text: '#ffffff' },
  teal:   { bg: '#14b8a6', text: '#ffffff' },
  pink:   { bg: '#ec4899', text: '#ffffff' },
}

export const MOCK_SELLERS = [
  // ── CREATIVOS ──────────────────────────────────────────────
  {
    id: '1',
    name: 'Sofia Martínez',
    username: 'sofiamx',
    group: 'creativos',
    category: 'UX/UI',
    boothType: 'services',
    badge: 'local',
    tagline: 'Diseño que convierte visitantes en clientes',
    avatar: null,
    rating: 4.9,
    reviews: 127,
    is_verified: true,
    accent: 'blue',
    items: [
      { id: 's1', title: 'Diseño de App Móvil',   price: 'Desde $800 USD',   delivery: '7 días' },
      { id: 's2', title: 'Auditoría UX Completa', price: 'Desde $300 USD',   delivery: '3 días' },
      { id: 's3', title: 'Sistema de Diseño',     price: 'Desde $1,200 USD', delivery: '14 días' },
    ],
  },
  {
    id: '2',
    name: 'Carlos Reyes',
    username: 'carlosrey',
    group: 'creativos',
    category: 'Marketing',
    boothType: 'services',
    badge: 'local',
    tagline: 'Estrategias digitales con resultados medibles',
    avatar: null,
    rating: 4.8,
    reviews: 89,
    is_verified: true,
    accent: 'green',
    items: [
      { id: 's4', title: 'Estrategia de Contenido',      price: 'Desde $400 USD',     delivery: '5 días' },
      { id: 's5', title: 'Gestión de Redes Sociales',   price: 'Desde $600 USD/mes', delivery: 'Mensual' },
    ],
  },
  {
    id: '3',
    name: 'Ana Beltrán',
    username: 'anabeltran',
    group: 'creativos',
    category: 'Audiovisual',
    boothType: 'services',
    badge: 'local',
    tagline: 'Video branding que hace que te recuerden',
    avatar: null,
    rating: 5.0,
    reviews: 43,
    is_verified: true,
    accent: 'red',
    items: [
      { id: 's6', title: 'Video Corporativo', price: 'Desde $1,500 USD', delivery: '10 días' },
      { id: 's7', title: 'Reels para Redes',  price: 'Desde $250 USD',   delivery: '3 días' },
    ],
  },
  {
    id: '4',
    name: 'Miguel Torres',
    username: 'migueltd',
    group: 'creativos',
    category: 'UX/UI',
    boothType: 'services',
    badge: 'local',
    tagline: 'Interfaces premium para productos SaaS',
    avatar: null,
    rating: 4.7,
    reviews: 211,
    is_verified: false,
    accent: 'yellow',
    items: [
      { id: 's8', title: 'Landing Page',          price: 'Desde $500 USD', delivery: '5 días' },
      { id: 's9', title: 'Prototipo Interactivo', price: 'Desde $350 USD', delivery: '4 días' },
    ],
  },
  {
    id: '5',
    name: 'Lucía Vargas',
    username: 'luciav',
    group: 'creativos',
    category: 'Marketing',
    boothType: 'services',
    badge: 'local',
    tagline: 'SEO y performance para marcas que quieren crecer',
    avatar: null,
    rating: 4.6,
    reviews: 158,
    is_verified: true,
    accent: 'black',
    items: [
      { id: 's10', title: 'Auditoría SEO',        price: 'Desde $200 USD',     delivery: '2 días' },
      { id: 's11', title: 'Posicionamiento Web',  price: 'Desde $800 USD/mes', delivery: 'Mensual' },
    ],
  },
  // ── MODA & LIFESTYLE ────────────────────────────────────────
  {
    id: '6',
    name: 'Valeria Mora',
    username: 'valemora',
    group: 'moda',
    category: 'Moda',
    boothType: 'catalog',
    badge: 'hecho-en-cr',
    tagline: 'Ropa hecha a mano con telas locales costarricenses',
    avatar: null,
    rating: 4.8,
    reviews: 34,
    is_verified: true,
    accent: 'pink',
    items: [
      { id: 'p1', title: 'Blusa Bordada Tropical',  price: '₡18,000', image: null, stock: 5 },
      { id: 'p2', title: 'Vestido Lino Natural',    price: '₡32,000', image: null, stock: 3 },
      { id: 'p3', title: 'Set Playa (top + falda)', price: '₡27,000', image: null, stock: 7 },
      { id: 'p4', title: 'Bolso Tejido Artesanal',  price: '₡15,000', image: null, stock: 10 },
    ],
  },
  // ── PRODUCTOS CR ────────────────────────────────────────────
  {
    id: '7',
    name: 'Dulces de la Abuela',
    username: 'dulcesabuela',
    group: 'productos-cr',
    category: 'Alimentos',
    boothType: 'catalog',
    badge: 'hecho-en-cr',
    tagline: 'Repostería tradicional costarricense hecha con amor',
    avatar: null,
    rating: 5.0,
    reviews: 61,
    is_verified: true,
    accent: 'orange',
    items: [
      { id: 'p5', title: 'Cajeta de Coco (500g)',    price: '₡3,500', image: null, stock: 20 },
      { id: 'p6', title: 'Mantecadas x12',            price: '₡4,800', image: null, stock: 15 },
      { id: 'p7', title: 'Rosquillas de Maíz x20',   price: '₡5,200', image: null, stock: 12 },
      { id: 'p8', title: 'Caja Surtida (20 piezas)', price: '₡8,000', image: null, stock: 8 },
    ],
  },
  // ── TECNOLOGÍA ──────────────────────────────────────────────
  {
    id: '8',
    name: 'TechDeal CR',
    username: 'techdealcr',
    group: 'tecnologia',
    category: 'Móviles',
    boothType: 'catalog',
    badge: null,
    tagline: 'Smartphones outlet y reacondicionados con garantía',
    avatar: null,
    rating: 4.5,
    reviews: 203,
    is_verified: true,
    accent: 'teal',
    items: [
      { id: 'p9',  title: 'iPhone 13 128GB (Outlet)', price: '₡295,000', image: null, stock: 3 },
      { id: 'p10', title: 'Samsung S23 256GB',         price: '₡320,000', image: null, stock: 2 },
      { id: 'p11', title: 'Xiaomi Redmi Note 13',      price: '₡145,000', image: null, stock: 8 },
      { id: 'p12', title: 'AirPods Pro 2 (Outlet)',    price: '₡89,000',  image: null, stock: 5 },
    ],
  },
  // ── EDUCACIÓN ───────────────────────────────────────────────
  {
    id: '9',
    name: 'Rita Chinchilla',
    username: 'ritaeduca',
    group: 'educacion',
    category: 'Cursos',
    boothType: 'courses',
    badge: 'local',
    tagline: 'Aprende diseño gráfico desde cero, en español y a tu ritmo',
    avatar: null,
    rating: 4.9,
    reviews: 88,
    is_verified: true,
    accent: 'purple',
    items: [
      { id: 'c1', title: 'Diseño Gráfico Básico',         price: '₡25,000', duration: '8 horas',  level: 'Principiante' },
      { id: 'c2', title: 'Canva Pro para Emprendedores', price: '₡18,000', duration: '4 horas',  level: 'Principiante' },
      { id: 'c3', title: 'Branding para tu Negocio',      price: '₡35,000', duration: '12 horas', level: 'Intermedio' },
    ],
  },
  // ── LOCAL → ONLINE ──────────────────────────────────────────
  {
    id: '10',
    name: 'Soda La Esquina',
    username: 'sodalasquina',
    group: 'local',
    category: 'Local → Online',
    boothType: 'hybrid',
    badge: 'local',
    tagline: 'Comida casera de San José — pedidos al WhatsApp o aquí mismo',
    avatar: null,
    rating: 4.7,
    reviews: 112,
    is_verified: false,
    accent: 'yellow',
    items: [
      { id: 'p13', title: 'Casado Completo', price: '₡3,800', image: null, stock: null },
      { id: 'p14', title: 'Arroz con Pollo', price: '₡3,200', image: null, stock: null },
      { id: 'p15', title: 'Sopa Negra',      price: '₡2,500', image: null, stock: null },
    ],
    services: [
      { id: 's12', title: 'Almuerzo en el local',  price: 'Sin reserva',      delivery: 'Lun-Sáb 11am-3pm' },
      { id: 's13', title: 'Catering para eventos', price: 'Desde ₡80,000', delivery: 'Con 3 días de anticipación' },
    ],
  },
]

export const MOCK_USER = {
  id: 'user-1',
  name: 'Javier D.',
  email: 'javier@elitemarket.co',
  user_role: 'buyer',
  is_verified: false,
  avatar: null,
}
